# Generated by Django 4.1.7 on 2023-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='customer_full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='available',
            field=models.CharField(blank=True, default='Specify quanity availble', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='bar_code',
            field=models.CharField(blank=True, default='Specify bar code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='brand',
            field=models.CharField(blank=True, default='Specify brand', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='expire_date_in_month_year',
            field=models.CharField(blank=True, default='Specify Expire Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='is_raw_material',
            field=models.CharField(blank=True, default='Specify is raw material', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='product_category',
            field=models.CharField(blank=True, default='Specify product category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='product_description',
            field=models.CharField(blank=True, default='Specify product description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='product_model',
            field=models.CharField(blank=True, default='Specify product model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='purchase_price',
            field=models.CharField(blank=True, default='Specify purchase price', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='reorder_level',
            field=models.CharField(blank=True, default='Specify reorder level', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='sales_price',
            field=models.CharField(blank=True, default='Specify Sales Price', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='sku_code',
            field=models.CharField(blank=True, default='Specify sku or code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='unit_code',
            field=models.CharField(blank=True, default='specify unit code', max_length=100, null=True),
        ),
    ]
