# Generated by Django 4.1.7 on 2023-08-20 14:56

from django.db import migrations, models
import storeApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_invoicenumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoicenumbers',
            name='invoice_no',
            field=models.CharField(blank=True, default=storeApp.models.increment_invoice_number, max_length=500, null=True),
        ),
    ]
