# Generated by Django 4.1.7 on 2023-08-06 05:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeApp', '0003_alter_productsoldincash_shop_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number_of_product_nedeed', models.IntegerField()),
                ('date_product_sold', models.DateTimeField(auto_now=True)),
                ('total_product_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('', 'Select type of Invoices'), ('profoma', 'Profoma'), ('unPaidInvoice', 'unPaidInvoice'), ('paidInvoice', 'paidInvoice'), ('cancelledInvoice', 'cancelledInvoice')], max_length=100, null=True)),
                ('date_for_issues_invoice', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_full_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storeApp.customerdetails')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeApp.producttable')),
                ('shop_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storeApp.shopstable')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'All Invoices',
            },
        ),
    ]
