# Generated by Django 4.1.7 on 2023-08-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_manageinvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageinvoice',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
