# Generated by Django 4.1.7 on 2023-08-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_manageinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageinvoice',
            name='invoice_type',
        ),
        migrations.AddField(
            model_name='manageinvoice',
            name='advance_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manageinvoice',
            name='amount_remain_to_be_paid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
