# Generated by Django 4.1.7 on 2023-08-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_manageinvoice_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsoldincash',
            name='total_profit_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
